-- =============================================================================
-- CTRL — Database schema + seed data
-- The tables are created by SQLAlchemy models (authoritative), and this file's
-- INSERTs are executed by database/init_db.py to seed data. It is also valid to
-- run this whole file directly (e.g. `mysql < database/db.sql`).
-- Charset utf8mb4 is required for full i18n (Arabic, emoji, etc.).
-- =============================================================================

CREATE DATABASE IF NOT EXISTS `ctrl`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ctrl`;

-- Roles: Cashier < Moderator < Admin < SuperAdmin ----------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id`          INT AUTO_INCREMENT PRIMARY KEY,
  `name`        VARCHAR(50)  NOT NULL UNIQUE,
  `level`       INT          NOT NULL DEFAULT 0,
  `description` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Users: username + bcrypt password hash --------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id`            INT AUTO_INCREMENT PRIMARY KEY,
  `username`      VARCHAR(100) NOT NULL UNIQUE,
  `full_name`     VARCHAR(150) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active`     TINYINT(1)   NOT NULL DEFAULT 1,
  `locale`        VARCHAR(10)  NOT NULL DEFAULT 'en',
  `role_id`       INT          NOT NULL,
  `created_at`    DATETIME     DEFAULT CURRENT_TIMESTAMP,
  `updated_at`    DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_users_role` FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Action logs: every meaningful action ---------------------------------------
CREATE TABLE IF NOT EXISTS `action_logs` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `user_id`    INT          NULL,
  `action`     VARCHAR(100) NOT NULL,
  `entity`     VARCHAR(100) NULL,
  `entity_id`  VARCHAR(100) NULL,
  `details`    TEXT         NULL,
  `status`     VARCHAR(20)  NOT NULL DEFAULT 'success',
  `ip_address` VARCHAR(64)  NULL,
  `user_agent` VARCHAR(255) NULL,
  `created_at` DATETIME     DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_logs_user` (`user_id`),
  KEY `idx_logs_action` (`action`),
  KEY `idx_logs_created` (`created_at`),
  CONSTRAINT `fk_logs_user` FOREIGN KEY (`user_id`)
    REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Translations: backend-managed i18n (en, ar, + future locales) ---------------
CREATE TABLE IF NOT EXISTS `translations` (
  `id`        INT AUTO_INCREMENT PRIMARY KEY,
  `namespace` VARCHAR(100) NOT NULL DEFAULT 'common',
  `key`       VARCHAR(150) NOT NULL,
  `locale`    VARCHAR(10)  NOT NULL,
  `value`     TEXT         NOT NULL,
  UNIQUE KEY `uq_translation` (`namespace`, `key`, `locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Settings: DB-configurable app settings (brand, currency, ...) ---------------
CREATE TABLE IF NOT EXISTS `settings` (
  `key`   VARCHAR(100) PRIMARY KEY,
  `value` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Categories: bilingual (en/ar), extensible to more locales -------------------
-- Images stored as base64 directly in the DB (no filesystem folder) -----------
CREATE TABLE IF NOT EXISTS `images` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `data`       LONGTEXT     NOT NULL,
  `mime`       VARCHAR(100) NOT NULL DEFAULT 'image/png',
  `created_at` DATETIME     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `categories` (
  `id`          INT AUTO_INCREMENT PRIMARY KEY,
  `name_en`     VARCHAR(120) NOT NULL,
  `name_ar`     VARCHAR(120) NOT NULL,
  `description` TEXT         NULL,
  `image_id`    INT          NULL,
  `is_active`   TINYINT(1)   NOT NULL DEFAULT 1,
  CONSTRAINT `fk_categories_image` FOREIGN KEY (`image_id`)
    REFERENCES `images`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Suppliers -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppliers` (
  `id`        INT AUTO_INCREMENT PRIMARY KEY,
  `name`      VARCHAR(180) NOT NULL,
  `phone`     VARCHAR(60)  NULL,
  `email`      VARCHAR(180) NULL,
  `address`    TEXT         NULL,
  `is_active`  TINYINT(1)   NOT NULL DEFAULT 1,
  `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Supplier invoices -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS `supplier_invoices` (
  `id`          INT AUTO_INCREMENT PRIMARY KEY,
  `supplier_id` INT           NOT NULL,
  `name`         VARCHAR(255)  NOT NULL,
  `quantity`     INT           NOT NULL DEFAULT 0,
  `amount`       DECIMAL(12,2) NOT NULL DEFAULT 0,
  `invoice_date` DATE          NULL,
  `image_url`    VARCHAR(512)  NULL,
  `created_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_invoice_supplier` FOREIGN KEY (`supplier_id`)
    REFERENCES `suppliers` (`id`) ON DELETE CASCADE,
  INDEX `ix_invoice_supplier` (`supplier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attribute definitions (Color, Size, ...) -----------------------------------
CREATE TABLE IF NOT EXISTS `attributes` (
  `id`          INT AUTO_INCREMENT PRIMARY KEY,
  `key`         VARCHAR(60)  NOT NULL UNIQUE,
  `type`        VARCHAR(20)  NOT NULL DEFAULT 'text',
  `name_en`     VARCHAR(120) NOT NULL,
  `name_ar`     VARCHAR(120) NOT NULL,
  `is_required` TINYINT(1)   NOT NULL DEFAULT 0,
  -- Global: one value shared across the whole product (coding requires NOT global).
  `is_global`   TINYINT(1)   NOT NULL DEFAULT 0,
  `coding`      TINYINT(1)   NOT NULL DEFAULT 0,
  `sort_order`  INT DEFAULT 0,
  `is_active`   TINYINT(1)   NOT NULL DEFAULT 1,
  `is_deleted`  TINYINT(1)   NOT NULL DEFAULT 0,
  `deleted_at`  DATETIME     NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attribute_values` (
  `id`           INT AUTO_INCREMENT PRIMARY KEY,
  `attribute_id` INT NOT NULL,
  `value_en`     VARCHAR(120) NOT NULL,
  `value_ar`     VARCHAR(120) NOT NULL,
  `extra`        JSON NULL,
  `sort_order`   INT DEFAULT 0,
  `is_deleted`   TINYINT(1)   NOT NULL DEFAULT 0,
  KEY `idx_attrval_attr` (`attribute_id`),
  CONSTRAINT `fk_attrval_attr` FOREIGN KEY (`attribute_id`)
    REFERENCES `attributes`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products (shared info) ------------------------------------------------------
-- Prices are float. `tags` is JSON. Deletion is a SOFT delete.
CREATE TABLE IF NOT EXISTS `products` (
  `id`                INT AUTO_INCREMENT PRIMARY KEY,
  `code`              VARCHAR(32)  NOT NULL,
  `name`              VARCHAR(255) NOT NULL,
  `description`       TEXT         NULL,
  `category_id`       INT          NULL,
  `supplier_id`       INT          NULL,
  `supplier_price`    DECIMAL(12,2) DEFAULT 0,
  `min_price`         DECIMAL(12,2) DEFAULT 0,
  `price`             DECIMAL(12,2) DEFAULT 0,
  `note`              TEXT         NULL,
  `tags`              JSON         NULL,
  `attributes`        JSON         NULL,
  `is_deleted`        TINYINT(1)   NOT NULL DEFAULT 0,
  `deleted_at`        DATETIME     NULL,
  `created_at`        DATETIME     DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_products_code` (`code`),
  KEY `idx_products_deleted` (`is_deleted`),
  CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`),
  CONSTRAINT `fk_products_supplier` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product variants = CODE UNITS (one per coding-attribute combo) --------------
-- Owns the unique code + images. `attributes` is JSON {attr_id: value_id} of the
-- CODING attributes only. `quantity` is legacy (on-hand now lives per stock unit).
CREATE TABLE IF NOT EXISTS `product_variants` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `product_id` INT NOT NULL,
  `code`       VARCHAR(32) NOT NULL UNIQUE,
  `attributes` JSON NULL,
  `quantity`   INT NOT NULL DEFAULT 0,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_variant_product` (`product_id`),
  KEY `idx_variant_code` (`code`),
  CONSTRAINT `fk_variant_product` FOREIGN KEY (`product_id`)
    REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Variant stock units = sellable SKUs (non-global, non-coding attr combos) ------
-- `attributes` is JSON {attr_id: value_id} of the non-global, non-coding
-- attributes; `quantity` is the on-hand count for that exact combination.
CREATE TABLE IF NOT EXISTS `product_variant_stocks` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `variant_id` INT NOT NULL,
  `attributes` JSON NULL,
  `quantity`   INT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_stock_variant` (`variant_id`),
  CONSTRAINT `fk_stock_variant` FOREIGN KEY (`variant_id`)
    REFERENCES `product_variants`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product images (up to 5 per variant) ----------------------------------------
CREATE TABLE IF NOT EXISTS `product_images` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `variant_id` INT NOT NULL,
  `url`        VARCHAR(512) NOT NULL,
  `sort_order` INT DEFAULT 0,
  KEY `idx_pimg_variant` (`variant_id`),
  CONSTRAINT `fk_pimg_variant` FOREIGN KEY (`variant_id`)
    REFERENCES `product_variants`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Point of Sale: customers, payment methods, sales, holds ---------------------
CREATE TABLE IF NOT EXISTS `customers` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `phone`      VARCHAR(40)  NULL UNIQUE,
  `name`       VARCHAR(180) NOT NULL,
  `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payment_methods` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `code`       VARCHAR(40) NOT NULL UNIQUE,
  `name_en`    VARCHAR(80) NOT NULL,
  `name_ar`    VARCHAR(80) NOT NULL,
  `is_active`  TINYINT(1)  NOT NULL DEFAULT 1,
  `sort_order` INT         NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sales` (
  `id`                INT AUTO_INCREMENT PRIMARY KEY,
  `invoice_no`        VARCHAR(32) NOT NULL UNIQUE,
  `user_id`           INT NULL,
  `customer_id`       INT NULL,
  `payment_method_id` INT NULL,
  `item_count`        INT           NOT NULL DEFAULT 0,
  `subtotal`          DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount`          DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total`             DECIMAL(12,2) NOT NULL DEFAULT 0,
  `paid_amount`       DECIMAL(12,2) NOT NULL DEFAULT 0,
  `change_amount`     DECIMAL(12,2) NOT NULL DEFAULT 0,
  `change_raw`        DECIMAL(12,2) NOT NULL DEFAULT 0,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_sales_user` (`user_id`),
  KEY `idx_sales_customer` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_items` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `sale_id`    INT NOT NULL,
  `product_id` INT NULL,
  `variant_id` INT NULL,
  `stock_id`   INT NULL,
  `code`       VARCHAR(32)  NOT NULL,
  `name`       VARCHAR(255) NOT NULL,
  `attributes` JSON NULL,
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `list_price` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `min_price`  DECIMAL(12,2) NOT NULL DEFAULT 0,
  `quantity`   INT           NOT NULL DEFAULT 0,
  `line_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  KEY `idx_sitem_sale` (`sale_id`),
  KEY `idx_sitem_variant` (`variant_id`),
  KEY `idx_sitem_stock` (`stock_id`),
  CONSTRAINT `fk_sitem_sale` FOREIGN KEY (`sale_id`)
    REFERENCES `sales`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Holds reserve a STOCK unit (per cashier tab). Transient (2h TTL).
CREATE TABLE IF NOT EXISTS `sale_holds` (
  `id`         INT AUTO_INCREMENT PRIMARY KEY,
  `hold_key`   VARCHAR(64) NOT NULL,
  `stock_id`   INT NOT NULL,
  `quantity`   INT NOT NULL DEFAULT 0,
  `flexible`   TINYINT(1) NOT NULL DEFAULT 0,
  `user_id`    INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_hold_key_stock` (`hold_key`, `stock_id`),
  KEY `idx_hold_key` (`hold_key`),
  KEY `idx_hold_stock` (`stock_id`),
  CONSTRAINT `fk_hold_stock` FOREIGN KEY (`stock_id`)
    REFERENCES `product_variant_stocks`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================ SEED DATA ======================================

-- Roles -----------------------------------------------------------------------
INSERT IGNORE INTO `roles` (`name`, `level`, `description`) VALUES
  ('Cashier',    10, 'Operates the point of sale.'),
  ('Moderator',  20, 'Manages catalog and day-to-day operations.'),
  ('Admin',      30, 'Full administrative access to the store.'),
  ('SuperAdmin', 40, 'Unrestricted, top-level system access.');

-- Seed SuperAdmin -------------------------------------------------------------
-- Username: admin   Password: Oselfasads@2
-- password_hash below is a bcrypt hash of the password above (never stored plaintext).
INSERT IGNORE INTO `users`
  (`username`, `full_name`, `password_hash`, `is_active`, `locale`, `role_id`)
SELECT
  'admin',
  'Super Administrator',
  '$2b$12$vT0W9.l3tIAwA1pFqVUDauderQCtJb8GnEgqNlfAnfisa5lOGpHK2',
  1,
  'en',
  r.`id`
FROM `roles` r
WHERE r.`name` = 'SuperAdmin';

-- Brand + currency (configurable in the database) -----------------------------
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES
  ('brand_name',  'CTRL'),
  ('brand_motto', 'Stay in CTRL.'),
  ('currency',    'EGP'),
  ('customer_phone_regex', '^(?:\\+20|0)1[0125]\\d{8}$');

-- Payment methods (configurable) ----------------------------------------------
INSERT IGNORE INTO `payment_methods` (`id`, `code`, `name_en`, `name_ar`, `is_active`, `sort_order`) VALUES
  (1, 'cash', 'Cash',      'نقدي',        1, 1),
  (2, 'card', 'Bank Card', 'بطاقة بنكية', 1, 2);

-- Categories (bilingual) ------------------------------------------------------
INSERT IGNORE INTO `categories` (`id`, `name_en`, `name_ar`, `is_active`) VALUES
  (1, 'T-Shirt', 'تي شيرت', 1),
  (2, 'Shirt',   'قميص',    1),
  (3, 'Pants',   'بنطلون',  1);

-- Suppliers -------------------------------------------------------------------
INSERT IGNORE INTO `suppliers` (`id`, `name`, `phone`, `email`, `address`, `is_active`) VALUES
  (1, 'Default Supplier', NULL, NULL, 'Cairo, Egypt', 1),
  (2, 'Cairo Textiles',   NULL, NULL, '15 El-Moez St, Cairo, Egypt', 1);

-- Attribute definitions (Color, Size) + bilingual values ----------------------
-- Color opts into `coding` (per code unit); Size is non-global + non-coding, so
-- it becomes a per-stock attribute the cashier can switch at the POS.
INSERT IGNORE INTO `attributes` (`id`, `key`, `type`, `name_en`, `name_ar`, `is_required`, `is_global`, `coding`, `sort_order`, `is_active`) VALUES
  (1, 'color', 'color', 'Color', 'اللون',   0, 0, 1, 1, 1),
  (2, 'size',  'text',  'Size',  'المقاس', 0, 0, 0, 2, 1);

INSERT IGNORE INTO `attribute_values` (`id`, `attribute_id`, `value_en`, `value_ar`, `extra`, `sort_order`) VALUES
  (1, 1, 'Red',   'أحمر', '{"hex": "#dc2626"}', 1),
  (2, 1, 'Blue',  'أزرق', '{"hex": "#2563eb"}', 2),
  (3, 1, 'Black', 'أسود', '{"hex": "#111111"}', 3),
  (4, 1, 'White', 'أبيض', '{"hex": "#f5f5f5"}', 4),
  (5, 1, 'Green', 'أخضر', '{"hex": "#16a34a"}', 5),
  (6, 2, 'S',  'صغير',       NULL, 1),
  (7, 2, 'M',  'وسط',        NULL, 2),
  (8, 2, 'L',  'كبير',       NULL, 3),
  (9, 2, 'XL', 'كبير جدًا',  NULL, 4);

-- Starter translations (en + ar; DB is the source of truth for UI strings) ---------------
INSERT IGNORE INTO `translations` (`namespace`, `key`, `locale`, `value`) VALUES
  ('common', 'welcome', 'ar', 'مرحبا'),
  ('common', 'welcome', 'en', 'Welcome'),
  ('ui', 'auth.genericError', 'ar', 'حدث خطأ ما. الرجاء المحاولة مرة أخرى.'),
  ('ui', 'auth.genericError', 'en', 'Something went wrong. Please try again.'),
  ('ui', 'auth.invalidCredentials', 'ar', 'اسم المستخدم أو كلمة المرور غير صحيحة.'),
  ('ui', 'auth.invalidCredentials', 'en', 'Invalid username or password.'),
  ('ui', 'auth.password', 'ar', 'كلمة المرور'),
  ('ui', 'auth.password', 'en', 'Password'),
  ('ui', 'auth.passwordPlaceholder', 'ar', 'أدخل كلمة المرور'),
  ('ui', 'auth.passwordPlaceholder', 'en', 'Enter your password'),
  ('ui', 'auth.rememberMe', 'ar', 'تذكرني'),
  ('ui', 'auth.rememberMe', 'en', 'Remember me'),
  ('ui', 'auth.signInButton', 'ar', 'تسجيل الدخول'),
  ('ui', 'auth.signInButton', 'en', 'Sign In'),
  ('ui', 'auth.signingIn', 'ar', 'جارٍ تسجيل الدخول'),
  ('ui', 'auth.signingIn', 'en', 'Signing in'),
  ('ui', 'auth.signInSubtitle', 'ar', 'أدخل اسم المستخدم وكلمة المرور.'),
  ('ui', 'auth.signInSubtitle', 'en', 'Enter your username and password.'),
  ('ui', 'auth.signInTitle', 'ar', 'تسجيل الدخول'),
  ('ui', 'auth.signInTitle', 'en', 'Sign In'),
  ('ui', 'auth.username', 'ar', 'اسم المستخدم'),
  ('ui', 'auth.username', 'en', 'Username'),
  ('ui', 'auth.usernamePlaceholder', 'ar', 'أدخل اسم المستخدم'),
  ('ui', 'auth.usernamePlaceholder', 'en', 'Enter your username'),
  ('ui', 'categories.add', 'ar', 'إضافة فئة'),
  ('ui', 'categories.add', 'en', 'Add Category'),
  ('ui', 'categories.bulk.apply', 'ar', 'تطبيق'),
  ('ui', 'categories.bulk.apply', 'en', 'Apply'),
  ('ui', 'categories.bulk.applying', 'ar', 'جارٍ التطبيق'),
  ('ui', 'categories.bulk.applying', 'en', 'Applying'),
  ('ui', 'categories.bulk.cancel', 'ar', 'إلغاء'),
  ('ui', 'categories.bulk.cancel', 'en', 'Cancel'),
  ('ui', 'categories.bulk.confirm', 'ar', 'حذف'),
  ('ui', 'categories.bulk.confirm', 'en', 'Delete'),
  ('ui', 'categories.bulk.confirmBody', 'ar', 'حذف {{count}} فئة محددة؟ سيتم تخطي أي فئة لا تزال مستخدمة في منتجات.'),
  ('ui', 'categories.bulk.confirmBody', 'en', 'Delete {{count}} selected categories? Any category still used by products will be skipped.'),
  ('ui', 'categories.bulk.confirmTitle', 'ar', 'حذف الفئات'),
  ('ui', 'categories.bulk.confirmTitle', 'en', 'Delete categories'),
  ('ui', 'categories.bulk.hint', 'ar', 'فعّل حقلاً لتغييره لكل الفئات المحددة.'),
  ('ui', 'categories.bulk.hint', 'en', 'Enable a field to change it for all selected categories.'),
  ('ui', 'categories.bulk.noFields', 'ar', 'فعّل حقلاً واحدًا على الأقل للتغيير.'),
  ('ui', 'categories.bulk.noFields', 'en', 'Enable at least one field to change.'),
  ('ui', 'categories.bulk.result', 'ar', 'تم حذف {{deleted}}، وتم تخطي {{blocked}} قيد الاستخدام.'),
  ('ui', 'categories.bulk.result', 'en', 'Deleted {{deleted}}, skipped {{blocked}} in use.'),
  ('ui', 'categories.bulk.title', 'ar', 'تعديل {{count}} فئة'),
  ('ui', 'categories.bulk.title', 'en', 'Edit {{count}} categories'),
  ('ui', 'categories.bulk.updated', 'ar', 'تم تحديث {{count}} فئة.'),
  ('ui', 'categories.bulk.updated', 'en', '{{count}} categories updated.'),
  ('ui', 'categories.bulkDelete', 'ar', 'حذف المحدد'),
  ('ui', 'categories.bulkDelete', 'en', 'Delete selected'),
  ('ui', 'categories.bulkEdit', 'ar', 'تعديل المحدد'),
  ('ui', 'categories.bulkEdit', 'en', 'Edit selected'),
  ('ui', 'categories.clearSelection', 'ar', 'مسح'),
  ('ui', 'categories.clearSelection', 'en', 'Clear'),
  ('ui', 'categories.confirmDelete.blocked', 'ar', '"{{name}}" مستخدمة في {{count}} منتج ولا يمكن حذفها.'),
  ('ui', 'categories.confirmDelete.blocked', 'en', '"{{name}}" is used by {{count}} product(s) and cannot be deleted.'),
  ('ui', 'categories.confirmDelete.body', 'ar', 'هل أنت متأكد من حذف "{{name}}"؟'),
  ('ui', 'categories.confirmDelete.body', 'en', 'Are you sure you want to delete "{{name}}"?'),
  ('ui', 'categories.confirmDelete.cancel', 'ar', 'إلغاء'),
  ('ui', 'categories.confirmDelete.cancel', 'en', 'Cancel'),
  ('ui', 'categories.confirmDelete.confirm', 'ar', 'حذف'),
  ('ui', 'categories.confirmDelete.confirm', 'en', 'Delete'),
  ('ui', 'categories.confirmDelete.deleted', 'ar', 'تم حذف الفئة.'),
  ('ui', 'categories.confirmDelete.deleted', 'en', 'Category deleted.'),
  ('ui', 'categories.confirmDelete.title', 'ar', 'حذف الفئة'),
  ('ui', 'categories.confirmDelete.title', 'en', 'Delete category'),
  ('ui', 'categories.copy', 'ar', 'نسخ'),
  ('ui', 'categories.copy', 'en', 'Copy'),
  ('ui', 'categories.delete', 'ar', 'حذف'),
  ('ui', 'categories.delete', 'en', 'Delete'),
  ('ui', 'categories.detail.close', 'ar', 'إغلاق'),
  ('ui', 'categories.detail.close', 'en', 'Close'),
  ('ui', 'categories.detail.description', 'ar', 'الوصف'),
  ('ui', 'categories.detail.description', 'en', 'Description'),
  ('ui', 'categories.detail.products', 'ar', 'المنتجات التي تستخدم هذه الفئة'),
  ('ui', 'categories.detail.products', 'en', 'Products using this category'),
  ('ui', 'categories.detail.title', 'ar', 'تفاصيل الفئة'),
  ('ui', 'categories.detail.title', 'en', 'Category Details'),
  ('ui', 'categories.edit', 'ar', 'تعديل'),
  ('ui', 'categories.edit', 'en', 'Edit'),
  ('ui', 'categories.empty', 'ar', 'لا توجد فئات بعد'),
  ('ui', 'categories.empty', 'en', 'No categories yet'),
  ('ui', 'categories.emptyBody', 'ar', 'أضف أول فئة للبدء.'),
  ('ui', 'categories.emptyBody', 'en', 'Add your first category to get started.'),
  ('ui', 'categories.errors.bothTaken', 'ar', 'كل من الاسم الإنجليزي والعربي مستخدم بالفعل في فئات أخرى.'),
  ('ui', 'categories.errors.bothTaken', 'en', 'Both the English and Arabic names are already used by other categories.'),
  ('ui', 'categories.errors.nameArTaken', 'ar', 'هذا الاسم العربي مستخدم بالفعل في فئة أخرى.'),
  ('ui', 'categories.errors.nameArTaken', 'en', 'This Arabic name is already used by another category.'),
  ('ui', 'categories.errors.nameEnTaken', 'ar', 'هذا الاسم الإنجليزي مستخدم بالفعل في فئة أخرى.'),
  ('ui', 'categories.errors.nameEnTaken', 'en', 'This English name is already used by another category.'),
  ('ui', 'categories.export', 'ar', 'تصدير'),
  ('ui', 'categories.export', 'en', 'Export'),
  ('ui', 'categories.import', 'ar', 'استيراد'),
  ('ui', 'categories.import', 'en', 'Import'),
  ('ui', 'categories.importDone', 'ar', 'تم استيراد {{count}} فئة.'),
  ('ui', 'categories.importDone', 'en', 'Imported {{count}} categories.'),
  ('ui', 'categories.importDoneSkipped', 'ar', 'تم استيراد {{count}} فئة، وتم تخطي {{skipped}} اسمًا مكررًا.'),
  ('ui', 'categories.importDoneSkipped', 'en', 'Imported {{count}} categories, skipped {{skipped}} duplicate name(s).'),
  ('ui', 'categories.modal.addImage', 'ar', 'رفع صورة'),
  ('ui', 'categories.modal.addImage', 'en', 'Upload image'),
  ('ui', 'categories.modal.addTitle', 'ar', 'إضافة فئة'),
  ('ui', 'categories.modal.addTitle', 'en', 'Add Category'),
  ('ui', 'categories.modal.cancel', 'ar', 'إلغاء'),
  ('ui', 'categories.modal.cancel', 'en', 'Cancel'),
  ('ui', 'categories.modal.copyTitle', 'ar', 'نسخ الفئة'),
  ('ui', 'categories.modal.copyTitle', 'en', 'Copy Category'),
  ('ui', 'categories.modal.created', 'ar', 'تم إنشاء الفئة.'),
  ('ui', 'categories.modal.created', 'en', 'Category created.'),
  ('ui', 'categories.modal.description', 'ar', 'الوصف'),
  ('ui', 'categories.modal.description', 'en', 'Description'),
  ('ui', 'categories.modal.editTitle', 'ar', 'تعديل الفئة'),
  ('ui', 'categories.modal.editTitle', 'en', 'Edit Category'),
  ('ui', 'categories.modal.image', 'ar', 'الصورة'),
  ('ui', 'categories.modal.image', 'en', 'Image'),
  ('ui', 'categories.modal.imageRequired', 'ar', 'الصورة مطلوبة.'),
  ('ui', 'categories.modal.imageRequired', 'en', 'An image is required.'),
  ('ui', 'categories.modal.nameAr', 'ar', 'الاسم (عربي)'),
  ('ui', 'categories.modal.nameAr', 'en', 'Name (AR)'),
  ('ui', 'categories.modal.nameEn', 'ar', 'الاسم (إنجليزي)'),
  ('ui', 'categories.modal.nameEn', 'en', 'Name (EN)'),
  ('ui', 'categories.modal.nameRequired', 'ar', 'الاسمان مطلوبان.'),
  ('ui', 'categories.modal.nameRequired', 'en', 'Both names are required.'),
  ('ui', 'categories.modal.save', 'ar', 'حفظ'),
  ('ui', 'categories.modal.save', 'en', 'Save'),
  ('ui', 'categories.modal.saving', 'ar', 'جارٍ الحفظ'),
  ('ui', 'categories.modal.saving', 'en', 'Saving'),
  ('ui', 'categories.modal.updated', 'ar', 'تم تحديث الفئة.'),
  ('ui', 'categories.modal.updated', 'en', 'Category updated.'),
  ('ui', 'categories.productsUsing', 'ar', '{{count}} منتج'),
  ('ui', 'categories.productsUsing', 'en', '{{count}} products'),
  ('ui', 'categories.search', 'ar', 'ابحث في الفئات'),
  ('ui', 'categories.search', 'en', 'Search categories'),
  ('ui', 'categories.selectAll', 'ar', 'تحديد الكل'),
  ('ui', 'categories.selectAll', 'en', 'Select all'),
  ('ui', 'categories.selectedCount', 'ar', '{{count}} محددة'),
  ('ui', 'categories.selectedCount', 'en', '{{count}} selected'),
  ('ui', 'categories.subtitle', 'ar', 'عرّف الفئات المستخدمة عبر المنتجات.'),
  ('ui', 'categories.subtitle', 'en', 'Define the categories used across products.'),
  ('ui', 'categories.title', 'ar', 'فئات المنتجات'),
  ('ui', 'categories.title', 'en', 'Product Categories'),
  ('ui', 'categories.view', 'ar', 'عرض'),
  ('ui', 'categories.view', 'en', 'View'),
  ('ui', 'common.arabic', 'ar', 'العربية'),
  ('ui', 'common.arabic', 'en', 'العربية'),
  ('ui', 'common.english', 'ar', 'English'),
  ('ui', 'common.english', 'en', 'English'),
  ('ui', 'common.language', 'ar', 'اللغة'),
  ('ui', 'common.language', 'en', 'Language'),
  ('ui', 'common.loading', 'ar', 'جارٍ التحميل'),
  ('ui', 'common.loading', 'en', 'Loading'),
  ('ui', 'common.search', 'ar', 'بحث'),
  ('ui', 'common.search', 'en', 'Search'),
  ('ui', 'common.signOut', 'ar', 'تسجيل الخروج'),
  ('ui', 'common.signOut', 'en', 'Sign out'),
  ('ui', 'dashboard.overview', 'ar', 'إليك ما يحدث في {{brand}} اليوم.'),
  ('ui', 'dashboard.overview', 'en', 'Here''s what''s happening in {{brand}} today.'),
  ('ui', 'dashboard.roleLabel', 'ar', 'الدور'),
  ('ui', 'dashboard.roleLabel', 'en', 'Role'),
  ('ui', 'dashboard.title', 'ar', 'لوحة التحكم'),
  ('ui', 'dashboard.title', 'en', 'Dashboard'),
  ('ui', 'dashboard.welcome', 'ar', 'مرحبًا بعودتك'),
  ('ui', 'dashboard.welcome', 'en', 'Welcome back'),
  ('ui', 'nav.dashboard', 'ar', 'لوحة التحكم'),
  ('ui', 'nav.dashboard', 'en', 'Dashboard'),
  ('ui', 'nav.menu', 'ar', 'القائمة'),
  ('ui', 'nav.menu', 'en', 'Menu'),
  ('ui', 'nav.productAttributes', 'ar', 'خصائص المنتجات'),
  ('ui', 'nav.productAttributes', 'en', 'Product Attributes'),
  ('ui', 'nav.productCategories', 'ar', 'فئات المنتجات'),
  ('ui', 'nav.productCategories', 'en', 'Product Categories'),
  ('ui', 'nav.productList', 'ar', 'قائمة المنتجات'),
  ('ui', 'nav.productList', 'en', 'Product List'),
  ('ui', 'nav.products', 'ar', 'المنتجات'),
  ('ui', 'nav.products', 'en', 'Products'),
  ('ui', 'nav.suppliers', 'ar', 'الموردون'),
  ('ui', 'nav.suppliers', 'en', 'Suppliers'),
  ('ui', 'products.addProduct', 'ar', 'إضافة منتج'),
  ('ui', 'products.addProduct', 'en', 'Add Product'),
  ('ui', 'products.addToCart', 'ar', 'أضف إلى السلة'),
  ('ui', 'products.addToCart', 'en', 'Add To Cart'),
  ('ui', 'products.addedToCart', 'en', 'Added to {{cart}}.'),
  ('ui', 'products.addedToCart', 'ar', 'تمت الإضافة إلى {{cart}}.'),
  ('ui', 'products.addSoldOut', 'en', 'This product is sold out.'),
  ('ui', 'products.addSoldOut', 'ar', 'هذا المنتج غير متوفر في المخزون.'),
  ('ui', 'products.chooseCart.title', 'en', 'Add to cart'),
  ('ui', 'products.chooseCart.title', 'ar', 'أضف إلى السلة'),
  ('ui', 'products.chooseCart.body', 'en', 'Choose a cart for {{name}}.'),
  ('ui', 'products.chooseCart.body', 'ar', 'اختر سلة للمنتج {{name}}.'),
  ('ui', 'products.chooseCart.items', 'en', '{{count}} items'),
  ('ui', 'products.chooseCart.items', 'ar', '{{count}} عنصر'),
  ('ui', 'products.bulk.apply', 'ar', 'تطبيق'),
  ('ui', 'products.bulk.apply', 'en', 'Apply'),
  ('ui', 'products.bulk.applying', 'ar', 'جارٍ التطبيق'),
  ('ui', 'products.bulk.applying', 'en', 'Applying'),
  ('ui', 'products.bulk.cancel', 'ar', 'إلغاء'),
  ('ui', 'products.bulk.cancel', 'en', 'Cancel'),
  ('ui', 'products.bulk.confirm', 'ar', 'حذف'),
  ('ui', 'products.bulk.confirm', 'en', 'Delete'),
  ('ui', 'products.bulk.confirmBody', 'ar', 'سيتم حذف {{count}} منتج.'),
  ('ui', 'products.bulk.confirmBody', 'en', 'This will delete {{count}} products.'),
  ('ui', 'products.bulk.confirmTitle', 'ar', 'حذف المنتجات المحددة؟'),
  ('ui', 'products.bulk.confirmTitle', 'en', 'Delete selected products?'),
  ('ui', 'products.bulk.deleted', 'ar', 'تم حذف {{count}} منتج.'),
  ('ui', 'products.bulk.deleted', 'en', 'Deleted {{count}} products.'),
  ('ui', 'products.bulk.hint', 'ar', 'فعّل حقلاً لتطبيق قيمته على كل المنتجات المحددة.'),
  ('ui', 'products.bulk.hint', 'en', 'Enable a field to apply its value to every selected product.'),
  ('ui', 'products.bulk.noFields', 'ar', 'فعّل حقلاً واحدًا على الأقل للتحديث.'),
  ('ui', 'products.bulk.noFields', 'en', 'Enable at least one field to update.'),
  ('ui', 'products.bulk.title', 'ar', 'تعديل {{count}} منتج'),
  ('ui', 'products.bulk.title', 'en', 'Edit {{count}} products'),
  ('ui', 'products.bulk.updated', 'ar', 'تم تحديث {{count}} منتج.'),
  ('ui', 'products.bulk.updated', 'en', 'Updated {{count}} products.'),
  ('ui', 'products.bulkDelete', 'ar', 'حذف المحدد'),
  ('ui', 'products.bulkDelete', 'en', 'Delete selected'),
  ('ui', 'products.bulkEdit', 'ar', 'تعديل المحدد'),
  ('ui', 'products.bulkEdit', 'en', 'Edit selected'),
  ('ui', 'products.clearSelection', 'ar', 'إلغاء التحديد'),
  ('ui', 'products.clearSelection', 'en', 'Clear selection'),
  ('ui', 'products.selectAll', 'ar', 'تحديد الكل'),
  ('ui', 'products.selectAll', 'en', 'Select all'),
  ('ui', 'products.selectedCount', 'ar', 'تم تحديد {{count}}'),
  ('ui', 'products.selectedCount', 'en', '{{count}} selected'),
  ('ui', 'products.attrs.add', 'ar', 'إضافة خاصية'),
  ('ui', 'products.attrs.add', 'en', 'Add Attribute'),
  ('ui', 'products.attrs.addAttribute', 'ar', 'إضافة خاصية'),
  ('ui', 'products.attrs.addAttribute', 'en', 'Add attribute'),
  ('ui', 'products.attrs.addValue', 'ar', 'إضافة قيمة'),
  ('ui', 'products.attrs.addValue', 'en', 'Add value'),
  ('ui', 'products.attrs.close', 'ar', 'إغلاق'),
  ('ui', 'products.attrs.close', 'en', 'Close'),
  ('ui', 'products.attrs.col.actions', 'ar', 'إجراءات'),
  ('ui', 'products.attrs.col.actions', 'en', 'Actions'),
  ('ui', 'products.attrs.col.coding', 'ar', 'الترميز'),
  ('ui', 'products.attrs.col.coding', 'en', 'Coding'),
  ('ui', 'products.attrs.col.mandatory', 'ar', 'إلزامي'),
  ('ui', 'products.attrs.col.mandatory', 'en', 'Mandatory'),
  ('ui', 'products.attrs.col.name', 'ar', 'الاسم'),
  ('ui', 'products.attrs.col.name', 'en', 'Name'),
  ('ui', 'products.attrs.col.type', 'ar', 'النوع'),
  ('ui', 'products.attrs.col.type', 'en', 'Type'),
  ('ui', 'products.attrs.col.values', 'ar', 'القيم'),
  ('ui', 'products.attrs.col.values', 'en', 'Values'),
  ('ui', 'products.attrs.colorHex', 'ar', 'اللون'),
  ('ui', 'products.attrs.colorHex', 'en', 'Color'),
  ('ui', 'products.attrs.confirmDelete.body', 'ar', 'حذف "{{name}}"؟'),
  ('ui', 'products.attrs.confirmDelete.body', 'en', 'Delete "{{name}}"?'),
  ('ui', 'products.attrs.confirmDelete.cancel', 'ar', 'إلغاء'),
  ('ui', 'products.attrs.confirmDelete.cancel', 'en', 'Cancel'),
  ('ui', 'products.attrs.confirmDelete.confirm', 'ar', 'حذف'),
  ('ui', 'products.attrs.confirmDelete.confirm', 'en', 'Delete'),
  ('ui', 'products.attrs.confirmDelete.title', 'ar', 'حذف الخاصية'),
  ('ui', 'products.attrs.confirmDelete.title', 'en', 'Delete attribute'),
  ('ui', 'products.attrs.copy', 'ar', 'نسخ'),
  ('ui', 'products.attrs.copy', 'en', 'Copy'),
  ('ui', 'products.attrs.delete', 'ar', 'حذف'),
  ('ui', 'products.attrs.delete', 'en', 'Delete'),
  ('ui', 'products.attrs.deleteConfirm', 'ar', 'حذف هذه الخاصية وكل قيمها؟'),
  ('ui', 'products.attrs.deleteConfirm', 'en', 'Delete this attribute and all its values?'),
  ('ui', 'products.attrs.deleted', 'ar', 'تم حذف الخاصية.'),
  ('ui', 'products.attrs.deleted', 'en', 'Attribute deleted.'),
  ('ui', 'products.attrs.edit', 'ar', 'تعديل'),
  ('ui', 'products.attrs.edit', 'en', 'Edit'),
  ('ui', 'products.attrs.empty', 'ar', 'لا توجد خصائص بعد'),
  ('ui', 'products.attrs.empty', 'en', 'No attributes yet'),
  ('ui', 'products.attrs.emptyBody', 'ar', 'أضف أول خاصية لتعريف معاملات المنتج.'),
  ('ui', 'products.attrs.emptyBody', 'en', 'Add your first attribute to define product parameters.'),
  ('ui', 'products.attrs.errors.dupColorHex', 'ar', 'لا يمكن أن يتطابق لونان في قيمة اللون (Hex).'),
  ('ui', 'products.attrs.errors.dupColorHex', 'en', 'Two colours can''t share the same hex value.'),
  ('ui', 'products.attrs.errors.dupValueAr', 'ar', 'لا يمكن أن تتطابق قيمتان في النص العربي.'),
  ('ui', 'products.attrs.errors.dupValueAr', 'en', 'Two values can''t share the same Arabic text.'),
  ('ui', 'products.attrs.errors.dupValueEn', 'ar', 'لا يمكن أن تتطابق قيمتان في النص الإنجليزي.'),
  ('ui', 'products.attrs.errors.dupValueEn', 'en', 'Two values can''t share the same English text.'),
  ('ui', 'products.attrs.errors.inUse', 'ar', 'هذه الخاصية مستخدمة في منتجات ولا يمكن حذفها.'),
  ('ui', 'products.attrs.errors.inUse', 'en', 'This attribute is used by products and cannot be deleted.'),
  ('ui', 'products.attrs.errors.nameArUsed', 'ar', 'توجد خاصية بنفس الاسم العربي بالفعل.'),
  ('ui', 'products.attrs.errors.nameArUsed', 'en', 'An attribute with this Arabic name already exists.'),
  ('ui', 'products.attrs.errors.nameEnUsed', 'ar', 'توجد خاصية بنفس الاسم الإنجليزي بالفعل.'),
  ('ui', 'products.attrs.errors.nameEnUsed', 'en', 'An attribute with this English name already exists.'),
  ('ui', 'products.attrs.importDone', 'ar', 'تم استيراد {{count}} خاصية.'),
  ('ui', 'products.attrs.importDone', 'en', 'Imported {{count}} attributes.'),
  ('ui', 'products.attrs.importDoneSkipped', 'ar', 'تم استيراد {{count}}، وتم تخطي {{skipped}} مكررًا.'),
  ('ui', 'products.attrs.importDoneSkipped', 'en', 'Imported {{count}}, skipped {{skipped}} duplicate(s).'),
  ('ui', 'products.attrs.inUse', 'ar', 'قيد الاستخدام'),
  ('ui', 'products.attrs.inUse', 'en', 'In use'),
  ('ui', 'products.attrs.key', 'ar', 'المفتاح'),
  ('ui', 'products.attrs.key', 'en', 'Key'),
  ('ui', 'products.attrs.keyHint', 'ar', 'مثال: color، size'),
  ('ui', 'products.attrs.keyHint', 'en', 'e.g. color, size'),
  ('ui', 'products.attrs.modal.addTitle', 'ar', 'إضافة خاصية'),
  ('ui', 'products.attrs.modal.addTitle', 'en', 'Add Attribute'),
  ('ui', 'products.attrs.modal.addValue', 'ar', 'إضافة قيمة'),
  ('ui', 'products.attrs.modal.addValue', 'en', 'Add value'),
  ('ui', 'products.attrs.modal.cancel', 'ar', 'إلغاء'),
  ('ui', 'products.attrs.modal.cancel', 'en', 'Cancel'),
  ('ui', 'products.attrs.modal.close', 'ar', 'إغلاق'),
  ('ui', 'products.attrs.modal.close', 'en', 'Close'),
  ('ui', 'products.attrs.modal.code', 'ar', 'الرمز'),
  ('ui', 'products.attrs.modal.code', 'en', 'Code'),
  ('ui', 'products.attrs.modal.coding', 'ar', 'الترميز'),
  ('ui', 'products.attrs.modal.coding', 'en', 'Coding'),
  ('ui', 'products.attrs.modal.codingHint', 'ar', 'تحصل كل قيمة على رمز خاص بها يساعد في بناء رمز المنتج.'),
  ('ui', 'products.attrs.modal.codingHint', 'en', 'Each value gets its own code that helps build the product code.'),
  ('ui', 'products.attrs.modal.color', 'ar', 'اللون'),
  ('ui', 'products.attrs.modal.color', 'en', 'Color'),
  ('ui', 'products.attrs.modal.colorNameAr', 'ar', 'اسم اللون (عربي)'),
  ('ui', 'products.attrs.modal.colorNameAr', 'en', 'Color name (AR)'),
  ('ui', 'products.attrs.modal.colorNameEn', 'ar', 'اسم اللون (إنجليزي)'),
  ('ui', 'products.attrs.modal.colorNameEn', 'en', 'Color name (EN)'),
  ('ui', 'products.attrs.modal.copyTitle', 'ar', 'نسخ خاصية'),
  ('ui', 'products.attrs.modal.copyTitle', 'en', 'Copy Attribute'),
  ('ui', 'products.attrs.modal.created', 'ar', 'تم إنشاء الخاصية.'),
  ('ui', 'products.attrs.modal.created', 'en', 'Attribute created.'),
  ('ui', 'products.attrs.modal.editTitle', 'ar', 'تعديل خاصية'),
  ('ui', 'products.attrs.modal.editTitle', 'en', 'Edit Attribute'),
  ('ui', 'products.attrs.modal.inUseHint', 'ar', 'مستخدمة في منتجات — لا يمكن حذف القيم المستخدمة بالفعل.'),
  ('ui', 'products.attrs.modal.inUseHint', 'en', 'In use by products — values already in use can''t be removed.'),
  ('ui', 'products.attrs.modal.mandatory', 'ar', 'إلزامي'),
  ('ui', 'products.attrs.modal.mandatory', 'en', 'Mandatory'),
  ('ui', 'products.attrs.modal.mandatoryHint', 'ar', 'اجعل اختيار قيمة لهذه الخاصية إلزاميًا عند إضافة منتج.'),
  ('ui', 'products.attrs.modal.mandatoryHint', 'en', 'Require a value for this attribute when adding a product.'),
  ('ui', 'products.attrs.modal.nameAr', 'ar', 'الاسم (عربي)'),
  ('ui', 'products.attrs.modal.nameAr', 'en', 'Name (AR)'),
  ('ui', 'products.attrs.modal.nameEn', 'ar', 'الاسم (إنجليزي)'),
  ('ui', 'products.attrs.modal.nameEn', 'en', 'Name (EN)'),
  ('ui', 'products.attrs.modal.nameRequired', 'ar', 'الاسم مطلوب باللغتين.'),
  ('ui', 'products.attrs.modal.nameRequired', 'en', 'Name is required in both languages.'),
  ('ui', 'products.attrs.modal.noValues', 'ar', 'لا توجد قيم بعد.'),
  ('ui', 'products.attrs.modal.noValues', 'en', 'No values yet.'),
  ('ui', 'products.attrs.modal.number', 'ar', 'رقم'),
  ('ui', 'products.attrs.modal.number', 'en', 'Number'),
  ('ui', 'products.attrs.modal.valueRequired', 'ar', 'قيمة صحيحة مطلوبة.'),
  ('ui', 'products.attrs.modal.valueRequired', 'en', 'A valid value is required.'),
  ('ui', 'products.attrs.modal.save', 'ar', 'حفظ'),
  ('ui', 'products.attrs.modal.save', 'en', 'Save'),
  ('ui', 'products.attrs.modal.saving', 'ar', 'جارٍ الحفظ'),
  ('ui', 'products.attrs.modal.saving', 'en', 'Saving'),
  ('ui', 'products.attrs.modal.type', 'ar', 'النوع'),
  ('ui', 'products.attrs.modal.type', 'en', 'Type'),
  ('ui', 'products.attrs.modal.updated', 'ar', 'تم تحديث الخاصية.'),
  ('ui', 'products.attrs.modal.updated', 'en', 'Attribute updated.'),
  ('ui', 'products.attrs.modal.valueAr', 'ar', 'القيمة (عربي)'),
  ('ui', 'products.attrs.modal.valueAr', 'en', 'Value (AR)'),
  ('ui', 'products.attrs.modal.valueEn', 'ar', 'القيمة (إنجليزي)'),
  ('ui', 'products.attrs.modal.valueEn', 'en', 'Value (EN)'),
  ('ui', 'products.attrs.modal.values', 'ar', 'القيم'),
  ('ui', 'products.attrs.modal.values', 'en', 'Values'),
  ('ui', 'products.attrs.modal.viewTitle', 'ar', 'تفاصيل الخاصية'),
  ('ui', 'products.attrs.modal.viewTitle', 'en', 'Attribute Details'),
  ('ui', 'products.attrs.nameAr', 'ar', 'الاسم (عربي)'),
  ('ui', 'products.attrs.nameAr', 'en', 'Name (AR)'),
  ('ui', 'products.attrs.nameEn', 'ar', 'الاسم (إنجليزي)'),
  ('ui', 'products.attrs.nameEn', 'en', 'Name (EN)'),
  ('ui', 'products.attrs.no', 'ar', 'لا'),
  ('ui', 'products.attrs.no', 'en', 'No'),
  ('ui', 'products.attrs.save', 'ar', 'حفظ'),
  ('ui', 'products.attrs.save', 'en', 'Save'),
  ('ui', 'products.attrs.saved', 'ar', 'تم حفظ الخصائص.'),
  ('ui', 'products.attrs.saved', 'en', 'Attributes saved.'),
  ('ui', 'products.attrs.saving', 'ar', 'جارٍ الحفظ'),
  ('ui', 'products.attrs.saving', 'en', 'Saving'),
  ('ui', 'products.attrs.search', 'ar', 'ابحث في الخصائص'),
  ('ui', 'products.attrs.search', 'en', 'Search attributes'),
  ('ui', 'products.attrs.subtitle', 'ar', 'عرّف المعاملات والقيم التي يمكن أن تستخدمها منتجاتك.'),
  ('ui', 'products.attrs.subtitle', 'en', 'Define parameters and the values your products can use.'),
  ('ui', 'products.attrs.title', 'ar', 'خصائص المنتج'),
  ('ui', 'products.attrs.title', 'en', 'Product Attributes'),
  ('ui', 'products.attrs.type.color', 'ar', 'لون'),
  ('ui', 'products.attrs.type.color', 'en', 'Color'),
  ('ui', 'products.attrs.type.number', 'ar', 'رقم'),
  ('ui', 'products.attrs.type.number', 'en', 'Number'),
  ('ui', 'products.attrs.type.text', 'ar', 'نص'),
  ('ui', 'products.attrs.type.text', 'en', 'Text'),
  ('ui', 'products.attrs.valueAr', 'ar', 'القيمة (عربي)'),
  ('ui', 'products.attrs.valueAr', 'en', 'Value (AR)'),
  ('ui', 'products.attrs.valueEn', 'ar', 'القيمة (إنجليزي)'),
  ('ui', 'products.attrs.valueEn', 'en', 'Value (EN)'),
  ('ui', 'products.attrs.values', 'ar', 'القيم'),
  ('ui', 'products.attrs.values', 'en', 'Values'),
  ('ui', 'products.attrs.valuesCount', 'ar', '{{count}} قيمة'),
  ('ui', 'products.attrs.valuesCount', 'en', '{{count}} values'),
  ('ui', 'products.attrs.view', 'ar', 'عرض'),
  ('ui', 'products.attrs.view', 'en', 'View'),
  ('ui', 'products.attrs.yes', 'ar', 'نعم'),
  ('ui', 'products.attrs.yes', 'en', 'Yes'),
  ('ui', 'products.clearAll', 'ar', 'مسح الكل'),
  ('ui', 'products.clearAll', 'en', 'Clear All'),
  ('ui', 'products.clearAllConfirm.body', 'ar', 'سيؤدي هذا إلى إزالة كل المنتجات من المتجر. هل تريد المتابعة؟'),
  ('ui', 'products.clearAllConfirm.body', 'en', 'This removes every product from the store. Continue?'),
  ('ui', 'products.clearAllConfirm.cancel', 'ar', 'إلغاء'),
  ('ui', 'products.clearAllConfirm.cancel', 'en', 'Cancel'),
  ('ui', 'products.clearAllConfirm.confirm', 'ar', 'مسح الكل'),
  ('ui', 'products.clearAllConfirm.confirm', 'en', 'Clear all'),
  ('ui', 'products.clearAllConfirm.title', 'ar', 'مسح كل المنتجات'),
  ('ui', 'products.clearAllConfirm.title', 'en', 'Clear all products'),
  ('ui', 'products.clearAllDone', 'ar', 'تم مسح {{count}} منتجًا.'),
  ('ui', 'products.clearAllDone', 'en', 'Cleared {{count}} products.'),
  ('ui', 'products.cleared', 'ar', 'تم مسح عوامل التصفية.'),
  ('ui', 'products.cleared', 'en', 'Filters cleared.'),
  ('ui', 'products.confirmDelete.body', 'ar', 'هل أنت متأكد من حذف "{{name}}"؟'),
  ('ui', 'products.confirmDelete.body', 'en', 'Are you sure you want to delete "{{name}}"?'),
  ('ui', 'products.confirmDelete.cancel', 'ar', 'إلغاء'),
  ('ui', 'products.confirmDelete.cancel', 'en', 'Cancel'),
  ('ui', 'products.confirmDelete.confirm', 'ar', 'حذف'),
  ('ui', 'products.confirmDelete.confirm', 'en', 'Delete'),
  ('ui', 'products.confirmDelete.deleted', 'ar', 'تم حذف المنتج.'),
  ('ui', 'products.confirmDelete.deleted', 'en', 'Product deleted.'),
  ('ui', 'products.confirmDelete.title', 'ar', 'حذف المنتج'),
  ('ui', 'products.confirmDelete.title', 'en', 'Delete product'),
  ('ui', 'products.copy', 'ar', 'نسخ'),
  ('ui', 'products.copy', 'en', 'Copy'),
  ('ui', 'products.delete', 'ar', 'حذف'),
  ('ui', 'products.delete', 'en', 'Delete'),
  ('ui', 'products.detail.category', 'ar', 'الفئة'),
  ('ui', 'products.detail.category', 'en', 'Category'),
  ('ui', 'products.detail.close', 'ar', 'إغلاق'),
  ('ui', 'products.detail.close', 'en', 'Close'),
  ('ui', 'products.detail.description', 'ar', 'الوصف'),
  ('ui', 'products.detail.description', 'en', 'Description'),
  ('ui', 'products.detail.minPrice', 'ar', 'الأدنى'),
  ('ui', 'products.detail.minPrice', 'en', 'Min'),
  ('ui', 'products.detail.noImage', 'ar', 'لا توجد صورة'),
  ('ui', 'products.detail.noImage', 'en', 'No image'),
  ('ui', 'products.detail.note', 'ar', 'ملاحظة'),
  ('ui', 'products.detail.note', 'en', 'Note'),
  ('ui', 'products.detail.price', 'ar', 'السعر'),
  ('ui', 'products.detail.price', 'en', 'Price'),
  ('ui', 'products.detail.prices', 'ar', 'الأسعار'),
  ('ui', 'products.detail.prices', 'en', 'Prices'),
  ('ui', 'products.detail.quantity', 'ar', 'الكمية'),
  ('ui', 'products.detail.quantity', 'en', 'Quantity'),
  ('ui', 'products.detail.supplier', 'ar', 'المورّد'),
  ('ui', 'products.detail.supplier', 'en', 'Supplier'),
  ('ui', 'products.detail.supplierPrice', 'ar', 'المورّد'),
  ('ui', 'products.detail.supplierPrice', 'en', 'Supplier'),
  ('ui', 'products.detail.tags', 'ar', 'الوسوم'),
  ('ui', 'products.detail.tags', 'en', 'Tags'),
  ('ui', 'products.detail.title', 'ar', 'تفاصيل المنتج'),
  ('ui', 'products.detail.title', 'en', 'Product Details'),
  ('ui', 'products.detail.variants', 'ar', 'الأنواع'),
  ('ui', 'products.detail.variants', 'en', 'Variants'),
  ('ui', 'products.edit', 'ar', 'تعديل'),
  ('ui', 'products.edit', 'en', 'Edit'),
  ('ui', 'products.emptyBody', 'ar', 'أضف أول منتج للبدء.'),
  ('ui', 'products.emptyBody', 'en', 'Add your first product to get started.'),
  ('ui', 'products.emptyTitle', 'ar', 'لا توجد منتجات بعد'),
  ('ui', 'products.emptyTitle', 'en', 'No products yet'),
  ('ui', 'products.errors.imageTooLarge', 'ar', 'الصورة كبيرة جدًا على قاعدة البيانات. يرجى استخدام صورة أصغر.'),
  ('ui', 'products.errors.imageTooLarge', 'en', 'Image is too large for the database. Please use a smaller image.'),
  ('ui', 'products.export', 'ar', 'تصدير'),
  ('ui', 'products.export', 'en', 'Export'),
  ('ui', 'products.filters.all', 'ar', 'الكل'),
  ('ui', 'products.filters.all', 'en', 'All'),
  ('ui', 'products.filters.allCategories', 'ar', 'كل الفئات'),
  ('ui', 'products.filters.allCategories', 'en', 'All categories'),
  ('ui', 'products.filters.allSelected', 'ar', 'الكل محدد'),
  ('ui', 'products.filters.allSelected', 'en', 'All selected'),
  ('ui', 'products.filters.any', 'ar', 'الكل'),
  ('ui', 'products.filters.any', 'en', 'Any'),
  ('ui', 'products.filters.byCategory', 'ar', 'تصفية حسب الفئة'),
  ('ui', 'products.filters.byCategory', 'en', 'Filter by Category'),
  ('ui', 'products.filters.byColor', 'ar', 'حسب اللون'),
  ('ui', 'products.filters.byColor', 'en', 'By Color'),
  ('ui', 'products.filters.byDate', 'ar', 'تصفية حسب التاريخ'),
  ('ui', 'products.filters.byDate', 'en', 'Filter by Date'),
  ('ui', 'products.filters.byPrice', 'ar', 'حسب السعر'),
  ('ui', 'products.filters.byPrice', 'en', 'By Price'),
  ('ui', 'products.filters.bySize', 'ar', 'حسب المقاس'),
  ('ui', 'products.filters.bySize', 'en', 'By Size'),
  ('ui', 'products.filters.byStock', 'ar', 'حسب المخزون'),
  ('ui', 'products.filters.byStock', 'en', 'By Stock'),
  ('ui', 'products.filters.clear', 'ar', 'مسح'),
  ('ui', 'products.filters.clear', 'en', 'Clear'),
  ('ui', 'products.filters.from', 'ar', 'من'),
  ('ui', 'products.filters.from', 'en', 'From'),
  ('ui', 'products.filters.nSelected', 'ar', '{{count}} محدد'),
  ('ui', 'products.filters.nSelected', 'en', '{{count}} selected'),
  ('ui', 'products.filters.reset', 'ar', 'إعادة ضبط التصفية'),
  ('ui', 'products.filters.reset', 'en', 'Reset Filters'),
  ('ui', 'products.filters.searchCategory', 'ar', 'ابحث في الفئات'),
  ('ui', 'products.filters.searchCategory', 'en', 'Search categories'),
  ('ui', 'products.filters.searchValues', 'ar', 'ابحث في القيم'),
  ('ui', 'products.filters.searchValues', 'en', 'Search values'),
  ('ui', 'products.filters.selectAll', 'ar', 'تحديد الكل'),
  ('ui', 'products.filters.selectAll', 'en', 'Select all'),
  ('ui', 'products.filters.sortBy', 'ar', 'ترتيب حسب'),
  ('ui', 'products.filters.sortBy', 'en', 'Sort by'),
  ('ui', 'products.filters.stockAll', 'ar', 'الكل'),
  ('ui', 'products.filters.stockAll', 'en', 'All'),
  ('ui', 'products.filters.stockIn', 'ar', 'متوفر'),
  ('ui', 'products.filters.stockIn', 'en', 'In Stock'),
  ('ui', 'products.filters.stockOut', 'ar', 'نفد'),
  ('ui', 'products.filters.stockOut', 'en', 'Sold'),
  ('ui', 'products.filters.title', 'ar', 'التصفية'),
  ('ui', 'products.filters.title', 'en', 'Filters'),
  ('ui', 'products.filters.to', 'ar', 'إلى'),
  ('ui', 'products.filters.to', 'en', 'To'),
  ('ui', 'products.import', 'ar', 'استيراد'),
  ('ui', 'products.import', 'en', 'Import'),
  ('ui', 'products.importDone', 'ar', 'تم استيراد {{count}} منتج.'),
  ('ui', 'products.importDone', 'en', 'Imported {{count}} products.'),
  ('ui', 'products.manageAttributes', 'ar', 'الخصائص'),
  ('ui', 'products.manageAttributes', 'en', 'Attributes'),
  ('ui', 'products.modal.addAttribute', 'ar', 'إضافة خاصية'),
  ('ui', 'products.modal.addAttribute', 'en', 'Add attribute'),
  ('ui', 'products.modal.addCategory', 'ar', 'إضافة فئة'),
  ('ui', 'products.modal.addCategory', 'en', 'Add category'),
  ('ui', 'products.modal.addImage', 'ar', 'إضافة صورة'),
  ('ui', 'products.modal.addImage', 'en', 'Add image'),
  ('ui', 'products.modal.addSupplier', 'ar', 'إضافة مورّد'),
  ('ui', 'products.modal.addSupplier', 'en', 'Add supplier'),
  ('ui', 'products.modal.addValue', 'ar', 'إضافة قيمة'),
  ('ui', 'products.modal.addValue', 'en', 'Add value'),
  ('ui', 'products.modal.addValueTo', 'ar', 'إضافة قيمة إلى {{name}}'),
  ('ui', 'products.modal.addValueTo', 'en', 'Add value to {{name}}'),
  ('ui', 'products.modal.valueAdded', 'ar', 'تمت إضافة القيمة.'),
  ('ui', 'products.modal.valueAdded', 'en', 'Value added.'),
  ('ui', 'products.modal.searchValue', 'ar', 'بحث…'),
  ('ui', 'products.modal.searchValue', 'en', 'Search…'),
  ('ui', 'products.modal.noResults', 'ar', 'لا توجد نتائج'),
  ('ui', 'products.modal.noResults', 'en', 'No matches'),
  ('ui', 'products.modal.noAttributes', 'ar', 'لا توجد خصائص معرّفة. يمكن إدارتها من صفحة خصائص المنتجات.'),
  ('ui', 'products.modal.noAttributes', 'en', 'No attributes defined. Manage them in Product Attributes.'),
  ('ui', 'products.modal.addTitle', 'ar', 'إضافة منتج'),
  ('ui', 'products.modal.addTitle', 'en', 'Add Product'),
  ('ui', 'products.modal.addVariant', 'ar', 'إضافة نوع'),
  ('ui', 'products.modal.addVariant', 'en', 'Add variant'),
  ('ui', 'products.modal.attrColorHex', 'ar', 'اللون'),
  ('ui', 'products.modal.attrColorHex', 'en', 'Color'),
  ('ui', 'products.modal.attributes', 'ar', 'الخصائص (اللون / المقاس)'),
  ('ui', 'products.modal.attributes', 'en', 'Attributes (Color / Size)'),
  ('ui', 'products.modal.attrKey', 'ar', 'المفتاح'),
  ('ui', 'products.modal.attrKey', 'en', 'Key'),
  ('ui', 'products.modal.attrLabelAr', 'ar', 'التسمية (عربي)'),
  ('ui', 'products.modal.attrLabelAr', 'en', 'Label (AR)'),
  ('ui', 'products.modal.attrLabelEn', 'ar', 'التسمية (إنجليزي)'),
  ('ui', 'products.modal.attrLabelEn', 'en', 'Label (EN)'),
  ('ui', 'products.modal.attrValueAr', 'ar', 'القيمة (عربي)'),
  ('ui', 'products.modal.attrValueAr', 'en', 'Value (AR)'),
  ('ui', 'products.modal.attrValueEn', 'ar', 'القيمة (إنجليزي)'),
  ('ui', 'products.modal.attrValueEn', 'en', 'Value (EN)'),
  ('ui', 'products.modal.cancel', 'ar', 'إلغاء'),
  ('ui', 'products.modal.cancel', 'en', 'Cancel'),
  ('ui', 'products.modal.category', 'ar', 'الفئة'),
  ('ui', 'products.modal.category', 'en', 'Category'),
  ('ui', 'products.modal.categoryRequired', 'ar', 'الفئة مطلوبة.'),
  ('ui', 'products.modal.categoryRequired', 'en', 'Category is required.'),
  ('ui', 'products.modal.code', 'ar', 'الكود'),
  ('ui', 'products.modal.code', 'en', 'Code'),
  ('ui', 'products.modal.codeAuto', 'ar', 'اتركه فارغًا للتوليد التلقائي'),
  ('ui', 'products.modal.codeAuto', 'en', 'Leave blank to auto-generate'),
  ('ui', 'products.modal.codeInUse', 'ar', 'هذا الكود مستخدم بالفعل.'),
  ('ui', 'products.modal.codeInUse', 'en', 'This code is already in use.'),
  ('ui', 'products.modal.codeInvalid', 'ar', 'يجب أن يكون الكود 8 أحرف/أرقام بالضبط.'),
  ('ui', 'products.modal.codeInvalid', 'en', 'Code must be exactly 8 letters/numbers.'),
  ('ui', 'products.modal.color', 'ar', 'اللون'),
  ('ui', 'products.modal.color', 'en', 'Color'),
  ('ui', 'products.modal.copyTitle', 'ar', 'نسخ المنتج'),
  ('ui', 'products.modal.copyTitle', 'en', 'Copy Product'),
  ('ui', 'products.modal.created', 'ar', 'تم إنشاء المنتج.'),
  ('ui', 'products.modal.created', 'en', 'Product created.'),
  ('ui', 'products.modal.custom', 'ar', 'مخصص'),
  ('ui', 'products.modal.custom', 'en', 'Custom'),
  ('ui', 'products.modal.description', 'ar', 'الوصف'),
  ('ui', 'products.modal.description', 'en', 'Description'),
  ('ui', 'products.modal.editTitle', 'ar', 'تعديل المنتج'),
  ('ui', 'products.modal.editTitle', 'en', 'Edit Product'),
  ('ui', 'products.modal.images', 'ar', 'الصور (حتى 5)'),
  ('ui', 'products.modal.images', 'en', 'Images (up to 5)'),
  ('ui', 'products.modal.imageUnsupported', 'ar', 'نوع الصورة غير مدعوم. استخدم JPG أو PNG أو WEBP أو GIF.'),
  ('ui', 'products.modal.imageUnsupported', 'en', 'Unsupported image type. Use JPG, PNG, WEBP or GIF.'),
  ('ui', 'products.modal.imageUploadFailed', 'ar', 'تعذّر رفع "{{name}}".'),
  ('ui', 'products.modal.imageUploadFailed', 'en', 'Couldn''t upload "{{name}}".'),
  ('ui', 'products.modal.minPrice', 'ar', 'أقل سعر'),
  ('ui', 'products.modal.minPrice', 'en', 'Min Price'),
  ('ui', 'products.modal.name', 'ar', 'اسم المنتج'),
  ('ui', 'products.modal.name', 'en', 'Item Name'),
  ('ui', 'products.modal.nameDuplicate', 'ar', 'يوجد منتج آخر يستخدم هذا الاسم.'),
  ('ui', 'products.modal.nameDuplicate', 'en', 'Another product already uses this name.'),
  ('ui', 'products.modal.nameRequired', 'ar', 'اسم المنتج مطلوب.'),
  ('ui', 'products.modal.nameRequired', 'en', 'Item name is required.'),
  ('ui', 'products.modal.noAttributesHint', 'ar', 'لا توجد خصائص معرّفة، لذا للمنتج نوع واحد. عرّف الخصائص (اللون، المقاس...) لإضافة أنواع.'),
  ('ui', 'products.modal.noAttributesHint', 'en', 'No attributes defined, so this product has a single variant. Define attributes (Color, Size, ...) to add variants.'),
  ('ui', 'products.modal.note', 'ar', 'ملاحظة'),
  ('ui', 'products.modal.note', 'en', 'Note'),
  ('ui', 'products.modal.price', 'ar', 'السعر'),
  ('ui', 'products.modal.price', 'en', 'Price'),
  ('ui', 'products.modal.priceBelowMin', 'ar', 'لا يمكن أن يكون السعر أقل من أقل سعر.'),
  ('ui', 'products.modal.priceBelowMin', 'en', 'Price cannot be lower than the minimum price.'),
  ('ui', 'products.modal.productAttributes', 'ar', 'خصائص المنتج'),
  ('ui', 'products.modal.productAttributes', 'en', 'Product attributes'),
  ('ui', 'products.modal.productCode', 'ar', 'كود المنتج'),
  ('ui', 'products.modal.productCode', 'en', 'Product code'),
  ('ui', 'products.modal.quantity', 'ar', 'الكمية'),
  ('ui', 'products.modal.quantity', 'en', 'Quantity'),
  ('ui', 'products.modal.removeVariant', 'ar', 'حذف النوع'),
  ('ui', 'products.modal.removeVariant', 'en', 'Remove variant'),
  ('ui', 'products.modal.requiredAttr', 'ar', 'يرجى اختيار قيمة لـ "{{name}}".'),
  ('ui', 'products.modal.requiredAttr', 'en', 'Please select a value for "{{name}}".'),
  ('ui', 'products.modal.save', 'ar', 'حفظ'),
  ('ui', 'products.modal.save', 'en', 'Save'),
  ('ui', 'products.modal.saving', 'ar', 'جارٍ الحفظ'),
  ('ui', 'products.modal.saving', 'en', 'Saving'),
  ('ui', 'products.modal.selectCategory', 'ar', 'اختر الفئة'),
  ('ui', 'products.modal.selectCategory', 'en', 'Select category'),
  ('ui', 'products.modal.selectSupplier', 'ar', 'اختر المورّد'),
  ('ui', 'products.modal.selectSupplier', 'en', 'Select supplier'),
  ('ui', 'products.modal.selectValue', 'ar', '—'),
  ('ui', 'products.modal.selectValue', 'en', '—'),
  ('ui', 'products.modal.size', 'ar', 'المقاس'),
  ('ui', 'products.modal.size', 'en', 'Size'),
  ('ui', 'products.modal.supplier', 'ar', 'المورّد'),
  ('ui', 'products.modal.supplier', 'en', 'Supplier'),
  ('ui', 'products.modal.supplierPrice', 'ar', 'سعر المورّد'),
  ('ui', 'products.modal.supplierPrice', 'en', 'Supplier Price'),
  ('ui', 'products.modal.tags', 'ar', 'الوسوم'),
  ('ui', 'products.modal.tags', 'en', 'Tags'),
  ('ui', 'products.modal.tagsHint', 'ar', 'اضغط Enter لإضافة وسم'),
  ('ui', 'products.modal.tagsHint', 'en', 'Press Enter to add a tag'),
  ('ui', 'products.modal.updated', 'ar', 'تم تحديث المنتج.'),
  ('ui', 'products.modal.updated', 'en', 'Product updated.'),
  ('ui', 'products.modal.variant', 'ar', 'النوع {{n}}'),
  ('ui', 'products.modal.variant', 'en', 'Variant {{n}}'),
  ('ui', 'products.modal.variantImages', 'ar', 'الصور (حتى 5)'),
  ('ui', 'products.modal.variantImages', 'en', 'Images (up to 5)'),
  ('ui', 'products.modal.variantRequired', 'ar', 'يلزم نوع واحد على الأقل.'),
  ('ui', 'products.modal.variantRequired', 'en', 'At least one variant is required.'),
  ('ui', 'products.modal.variants', 'ar', 'الأنواع'),
  ('ui', 'products.modal.variants', 'en', 'Variants'),
  ('ui', 'products.inStock', 'ar', 'متوفر'),
  ('ui', 'products.inStock', 'en', 'In Stock'),
  ('ui', 'products.oneVariant', 'ar', 'نوع واحد'),
  ('ui', 'products.oneVariant', 'en', '1 variant'),
  ('ui', 'products.soldOut', 'ar', 'نفد المخزون'),
  ('ui', 'products.soldOut', 'en', 'Sold Out'),
  ('ui', 'products.pagination.next', 'ar', 'التالي'),
  ('ui', 'products.pagination.next', 'en', 'Next'),
  ('ui', 'products.pagination.pageOf', 'ar', 'صفحة {{page}} من {{pages}}'),
  ('ui', 'products.pagination.pageOf', 'en', 'Page {{page}} of {{pages}}'),
  ('ui', 'products.pagination.prev', 'ar', 'السابق'),
  ('ui', 'products.pagination.prev', 'en', 'Previous'),
  ('ui', 'products.resultsCount', 'ar', '{{count}} منتج'),
  ('ui', 'products.resultsCount', 'en', '{{count}} products'),
  ('ui', 'products.searchPlaceholder', 'ar', 'ابحث بالاسم أو الكود أو الوصف أو الوسوم'),
  ('ui', 'products.searchPlaceholder', 'en', 'Search by name, code, description or tags'),
  ('ui', 'products.sort.newest', 'ar', 'الأحدث'),
  ('ui', 'products.sort.newest', 'en', 'Newest'),
  ('ui', 'products.sort.popular', 'ar', 'الأكثر رواجًا'),
  ('ui', 'products.sort.popular', 'en', 'Popular'),
  ('ui', 'products.sort.priceHighLow', 'ar', 'السعر: من الأعلى للأقل'),
  ('ui', 'products.sort.priceHighLow', 'en', 'Price: High to Low'),
  ('ui', 'products.sort.priceLowHigh', 'ar', 'السعر: من الأقل للأعلى'),
  ('ui', 'products.sort.priceLowHigh', 'en', 'Price: Low to High'),
  ('ui', 'products.subtitle', 'ar', 'إدارة الكتالوج الخاص بك.'),
  ('ui', 'products.subtitle', 'en', 'Manage your catalog.'),
  ('ui', 'products.table.actions', 'ar', 'إجراءات'),
  ('ui', 'products.table.actions', 'en', 'Actions'),
  ('ui', 'products.table.category', 'ar', 'الفئة'),
  ('ui', 'products.table.category', 'en', 'Category'),
  ('ui', 'products.table.code', 'ar', 'الكود'),
  ('ui', 'products.table.code', 'en', 'Code'),
  ('ui', 'products.table.name', 'ar', 'الاسم'),
  ('ui', 'products.table.name', 'en', 'Name'),
  ('ui', 'products.table.price', 'ar', 'السعر'),
  ('ui', 'products.table.price', 'en', 'Price'),
  ('ui', 'products.table.quantity', 'ar', 'الكمية'),
  ('ui', 'products.table.quantity', 'en', 'Quantity'),
  ('ui', 'products.table.stock', 'ar', 'المخزون'),
  ('ui', 'products.table.stock', 'en', 'Stock'),
  ('ui', 'products.title', 'ar', 'المنتجات'),
  ('ui', 'products.title', 'en', 'Products'),
  ('ui', 'products.variantsCount', 'ar', '{{count}} أنواع'),
  ('ui', 'products.variantsCount', 'en', '{{count}} variants'),
  ('ui', 'products.viewAction', 'ar', 'عرض'),
  ('ui', 'products.viewAction', 'en', 'View'),
  ('ui', 'products.view.category', 'ar', 'الفئة'),
  ('ui', 'products.view.category', 'en', 'Category'),
  ('ui', 'products.view.close', 'ar', 'إغلاق'),
  ('ui', 'products.view.close', 'en', 'Close'),
  ('ui', 'products.view.description', 'ar', 'الوصف'),
  ('ui', 'products.view.description', 'en', 'Description'),
  ('ui', 'products.view.minPrice', 'ar', 'الأدنى'),
  ('ui', 'products.view.minPrice', 'en', 'Min'),
  ('ui', 'products.view.noImage', 'ar', 'لا توجد صورة'),
  ('ui', 'products.view.noImage', 'en', 'No image'),
  ('ui', 'products.view.note', 'ar', 'ملاحظة'),
  ('ui', 'products.view.note', 'en', 'Note'),
  ('ui', 'products.view.price', 'ar', 'السعر'),
  ('ui', 'products.view.price', 'en', 'Price'),
  ('ui', 'products.view.prices', 'ar', 'الأسعار'),
  ('ui', 'products.view.prices', 'en', 'Prices'),
  ('ui', 'products.view.supplier', 'ar', 'المورّد'),
  ('ui', 'products.view.supplier', 'en', 'Supplier'),
  ('ui', 'products.view.supplierPrice', 'ar', 'المورّد'),
  ('ui', 'products.view.supplierPrice', 'en', 'Supplier'),
  ('ui', 'products.view.tags', 'ar', 'الوسوم'),
  ('ui', 'products.view.tags', 'en', 'Tags'),
  ('ui', 'products.view.title', 'ar', 'تفاصيل المنتج'),
  ('ui', 'products.view.title', 'en', 'Product Details'),
  ('ui', 'products.view.variants', 'ar', 'الأنواع'),
  ('ui', 'products.view.variants', 'en', 'Variants'),
  ('ui', 'products.viewGrid', 'ar', 'عرض شبكي'),
  ('ui', 'products.viewGrid', 'en', 'Grid view'),
  ('ui', 'products.viewTable', 'ar', 'عرض القائمة'),
  ('ui', 'products.viewTable', 'en', 'List view');

-- Suppliers page -------------------------------------------------------------
INSERT IGNORE INTO `translations` (`namespace`, `key`, `locale`, `value`) VALUES
  ('ui', 'suppliers.title', 'en', 'Suppliers'),
  ('ui', 'suppliers.title', 'ar', 'الموردون'),
  ('ui', 'suppliers.subtitle', 'en', 'Manage the vendors that supply your products.'),
  ('ui', 'suppliers.subtitle', 'ar', 'إدارة الموردين الذين يزودون منتجاتك.'),
  ('ui', 'suppliers.add', 'en', 'Add Supplier'),
  ('ui', 'suppliers.add', 'ar', 'إضافة مورّد'),
  ('ui', 'suppliers.search', 'en', 'Search by name, phone or email'),
  ('ui', 'suppliers.search', 'ar', 'ابحث بالاسم أو الهاتف أو البريد'),
  ('ui', 'suppliers.empty', 'en', 'No suppliers yet'),
  ('ui', 'suppliers.empty', 'ar', 'لا يوجد موردون بعد'),
  ('ui', 'suppliers.emptyBody', 'en', 'Add your first supplier to get started.'),
  ('ui', 'suppliers.emptyBody', 'ar', 'أضف أول مورّد للبدء.'),
  ('ui', 'suppliers.view', 'en', 'View'),
  ('ui', 'suppliers.view', 'ar', 'عرض'),
  ('ui', 'suppliers.edit', 'en', 'Edit'),
  ('ui', 'suppliers.edit', 'ar', 'تعديل'),
  ('ui', 'suppliers.copy', 'en', 'Duplicate'),
  ('ui', 'suppliers.copy', 'ar', 'نسخ'),
  ('ui', 'suppliers.delete', 'en', 'Delete'),
  ('ui', 'suppliers.delete', 'ar', 'حذف'),
  ('ui', 'suppliers.detail.title', 'en', 'Supplier Details'),
  ('ui', 'suppliers.detail.title', 'ar', 'تفاصيل المورّد'),
  ('ui', 'suppliers.invoices.title', 'en', 'Invoices'),
  ('ui', 'suppliers.invoices.title', 'ar', 'الفواتير'),
  ('ui', 'suppliers.invoices.count', 'en', '{{count}} total'),
  ('ui', 'suppliers.invoices.count', 'ar', '{{count}} إجمالاً'),
  ('ui', 'suppliers.invoices.name', 'en', 'Invoice name'),
  ('ui', 'suppliers.invoices.name', 'ar', 'اسم الفاتورة'),
  ('ui', 'suppliers.invoices.quantity', 'en', 'Quantity'),
  ('ui', 'suppliers.invoices.quantity', 'ar', 'الكمية'),
  ('ui', 'suppliers.invoices.amount', 'en', 'Amount'),
  ('ui', 'suppliers.invoices.amount', 'ar', 'المبلغ'),
  ('ui', 'suppliers.invoices.date', 'en', 'Date'),
  ('ui', 'suppliers.invoices.date', 'ar', 'التاريخ'),
  ('ui', 'suppliers.invoices.dateRequired', 'en', 'Invoice date is required.'),
  ('ui', 'suppliers.invoices.dateRequired', 'ar', 'تاريخ الفاتورة مطلوب.'),
  ('ui', 'suppliers.invoices.someFailed', 'en', '{{count}} invoice(s) could not be saved.'),
  ('ui', 'suppliers.invoices.someFailed', 'ar', 'تعذّر حفظ {{count}} فاتورة.'),
  ('ui', 'suppliers.invoices.image', 'en', 'Image'),
  ('ui', 'suppliers.invoices.image', 'ar', 'الصورة'),
  ('ui', 'suppliers.invoices.add', 'en', 'Add'),
  ('ui', 'suppliers.invoices.add', 'ar', 'إضافة'),
  ('ui', 'suppliers.invoices.added', 'en', 'Invoice added.'),
  ('ui', 'suppliers.invoices.added', 'ar', 'تمت إضافة الفاتورة.'),
  ('ui', 'suppliers.invoices.deleted', 'en', 'Invoice deleted.'),
  ('ui', 'suppliers.invoices.deleted', 'ar', 'تم حذف الفاتورة.'),
  ('ui', 'suppliers.invoices.delete', 'en', 'Delete invoice'),
  ('ui', 'suppliers.invoices.delete', 'ar', 'حذف الفاتورة'),
  ('ui', 'suppliers.invoices.empty', 'en', 'No invoices for this supplier yet.'),
  ('ui', 'suppliers.invoices.empty', 'ar', 'لا توجد فواتير لهذا المورّد بعد.'),
  ('ui', 'suppliers.invoices.nameRequired', 'en', 'Invoice name is required.'),
  ('ui', 'suppliers.invoices.nameRequired', 'ar', 'اسم الفاتورة مطلوب.'),
  ('ui', 'suppliers.invoices.quantityRequired', 'en', 'A valid quantity is required.'),
  ('ui', 'suppliers.invoices.quantityRequired', 'ar', 'الكمية الصحيحة مطلوبة.'),
  ('ui', 'suppliers.invoices.amountRequired', 'en', 'A valid amount is required.'),
  ('ui', 'suppliers.invoices.amountRequired', 'ar', 'المبلغ الصحيح مطلوب.'),
  ('ui', 'suppliers.table.name', 'en', 'Name'),
  ('ui', 'suppliers.table.name', 'ar', 'الاسم'),
  ('ui', 'suppliers.table.phone', 'en', 'Phone'),
  ('ui', 'suppliers.table.phone', 'ar', 'الهاتف'),
  ('ui', 'suppliers.table.email', 'en', 'Email'),
  ('ui', 'suppliers.table.email', 'ar', 'البريد الإلكتروني'),
  ('ui', 'suppliers.table.address', 'en', 'Address'),
  ('ui', 'suppliers.table.address', 'ar', 'العنوان'),
  ('ui', 'suppliers.table.products', 'en', 'Products'),
  ('ui', 'suppliers.table.products', 'ar', 'المنتجات'),
  ('ui', 'suppliers.table.actions', 'en', 'Actions'),
  ('ui', 'suppliers.table.actions', 'ar', 'إجراءات'),
  ('ui', 'suppliers.stats.total', 'en', 'Total Suppliers'),
  ('ui', 'suppliers.stats.total', 'ar', 'إجمالي الموردين'),
  ('ui', 'suppliers.stats.spend', 'en', 'Paid to Suppliers'),
  ('ui', 'suppliers.stats.spend', 'ar', 'المدفوع للموردين'),
  ('ui', 'suppliers.stats.spendSub', 'en', 'Supplier price x stock on hand'),
  ('ui', 'suppliers.stats.spendSub', 'ar', 'سعر المورّد × المخزون المتوفر'),
  ('ui', 'suppliers.stats.products', 'en', 'Products Supplied'),
  ('ui', 'suppliers.stats.products', 'ar', 'منتجات مورّدة'),
  ('ui', 'suppliers.stats.newThisMonth', 'en', 'new this month'),
  ('ui', 'suppliers.stats.newThisMonth', 'ar', 'جديد هذا الشهر'),
  ('ui', 'suppliers.stats.boughtThisMonth', 'en', 'added this month'),
  ('ui', 'suppliers.stats.boughtThisMonth', 'ar', 'أُضيفت هذا الشهر'),
  ('ui', 'suppliers.stats.paidThisMonth', 'en', 'this month'),
  ('ui', 'suppliers.stats.paidThisMonth', 'ar', 'هذا الشهر'),
  ('ui', 'suppliers.stats.top', 'en', 'Top Supplier'),
  ('ui', 'suppliers.stats.top', 'ar', 'المورّد الأبرز'),
  ('ui', 'suppliers.stats.none', 'en', '—'),
  ('ui', 'suppliers.stats.none', 'ar', '—'),
  ('ui', 'suppliers.modal.addTitle', 'en', 'Add Supplier'),
  ('ui', 'suppliers.modal.addTitle', 'ar', 'إضافة مورّد'),
  ('ui', 'suppliers.modal.editTitle', 'en', 'Edit Supplier'),
  ('ui', 'suppliers.modal.editTitle', 'ar', 'تعديل المورّد'),
  ('ui', 'suppliers.modal.copyTitle', 'en', 'Duplicate Supplier'),
  ('ui', 'suppliers.modal.copyTitle', 'ar', 'نسخ المورّد'),
  ('ui', 'suppliers.modal.name', 'en', 'Name'),
  ('ui', 'suppliers.modal.name', 'ar', 'الاسم'),
  ('ui', 'suppliers.modal.phone', 'en', 'Phone'),
  ('ui', 'suppliers.modal.phone', 'ar', 'الهاتف'),
  ('ui', 'suppliers.modal.email', 'en', 'Email'),
  ('ui', 'suppliers.modal.email', 'ar', 'البريد الإلكتروني'),
  ('ui', 'suppliers.modal.address', 'en', 'Address'),
  ('ui', 'suppliers.modal.address', 'ar', 'العنوان'),
  ('ui', 'suppliers.modal.nameRequired', 'en', 'Supplier name is required.'),
  ('ui', 'suppliers.modal.nameRequired', 'ar', 'اسم المورّد مطلوب.'),
  ('ui', 'suppliers.modal.emailInvalid', 'en', 'Please enter a valid email address.'),
  ('ui', 'suppliers.modal.emailInvalid', 'ar', 'يرجى إدخال بريد إلكتروني صحيح.'),
  ('ui', 'suppliers.modal.addressRequired', 'en', 'Supplier address is required.'),
  ('ui', 'suppliers.modal.addressRequired', 'ar', 'عنوان المورّد مطلوب.'),
  ('ui', 'suppliers.modal.save', 'en', 'Save'),
  ('ui', 'suppliers.modal.save', 'ar', 'حفظ'),
  ('ui', 'suppliers.modal.saving', 'en', 'Saving…'),
  ('ui', 'suppliers.modal.saving', 'ar', 'جارٍ الحفظ…'),
  ('ui', 'suppliers.modal.cancel', 'en', 'Cancel'),
  ('ui', 'suppliers.modal.cancel', 'ar', 'إلغاء'),
  ('ui', 'suppliers.modal.created', 'en', 'Supplier created.'),
  ('ui', 'suppliers.modal.created', 'ar', 'تم إنشاء المورّد.'),
  ('ui', 'suppliers.modal.updated', 'en', 'Supplier updated.'),
  ('ui', 'suppliers.modal.updated', 'ar', 'تم تحديث المورّد.'),
  ('ui', 'suppliers.confirmDelete.title', 'en', 'Delete supplier'),
  ('ui', 'suppliers.confirmDelete.title', 'ar', 'حذف المورّد'),
  ('ui', 'suppliers.confirmDelete.body', 'en', 'Are you sure you want to delete "{{name}}"?'),
  ('ui', 'suppliers.confirmDelete.body', 'ar', 'هل أنت متأكد من حذف "{{name}}"؟'),
  ('ui', 'suppliers.confirmDelete.confirm', 'en', 'Delete'),
  ('ui', 'suppliers.confirmDelete.confirm', 'ar', 'حذف'),
  ('ui', 'suppliers.confirmDelete.cancel', 'en', 'Cancel'),
  ('ui', 'suppliers.confirmDelete.cancel', 'ar', 'إلغاء'),
  ('ui', 'suppliers.confirmDelete.deleted', 'en', 'Supplier deleted.'),
  ('ui', 'suppliers.confirmDelete.deleted', 'ar', 'تم حذف المورّد.'),
  ('ui', 'suppliers.confirmDelete.blocked', 'en', '"{{name}}" is used by {{count}} product(s) and cannot be deleted.'),
  ('ui', 'suppliers.confirmDelete.blocked', 'ar', 'المورّد "{{name}}" مستخدم في {{count}} منتج ولا يمكن حذفه.'),
  ('ui', 'suppliers.errors.nameTaken', 'en', 'A supplier with this name already exists.'),
  ('ui', 'suppliers.errors.nameTaken', 'ar', 'يوجد مورّد بهذا الاسم بالفعل.'),
  -- Navigation
  ('ui', 'nav.pos', 'en', 'Point of Sale'),
  ('ui', 'nav.pos', 'ar', 'نقطة البيع'),
  -- POS page
  ('ui', 'pos.title', 'en', 'Point of Sale'),
  ('ui', 'pos.title', 'ar', 'نقطة البيع'),
  ('ui', 'pos.subtitle', 'en', 'Scan products, manage carts and check out customers.'),
  ('ui', 'pos.subtitle', 'ar', 'امسح المنتجات وأدر السلال وأتمم عمليات البيع.'),
  ('ui', 'pos.tab', 'en', 'Cart {{n}}'),
  ('ui', 'pos.tab', 'ar', 'سلة {{n}}'),
  ('ui', 'pos.newTab', 'en', 'New cart'),
  ('ui', 'pos.newTab', 'ar', 'سلة جديدة'),
  ('ui', 'pos.maxTabs', 'en', 'You can open up to 5 carts at once.'),
  ('ui', 'pos.maxTabs', 'ar', 'يمكنك فتح حتى 5 سلال في وقت واحد.'),
  ('ui', 'pos.closeTab', 'en', 'Close cart'),
  ('ui', 'pos.closeTab', 'ar', 'إغلاق السلة'),
  ('ui', 'pos.closeConfirm.title', 'en', 'Close this cart?'),
  ('ui', 'pos.closeConfirm.title', 'ar', 'إغلاق هذه السلة؟'),
  ('ui', 'pos.closeConfirm.body', 'en', 'The cart items will be discarded and the held stock released.'),
  ('ui', 'pos.closeConfirm.body', 'ar', 'سيتم تجاهل عناصر السلة وتحرير المخزون المحجوز.'),
  ('ui', 'pos.closeConfirm.confirm', 'en', 'Close cart'),
  ('ui', 'pos.closeConfirm.confirm', 'ar', 'إغلاق السلة'),
  ('ui', 'pos.closeConfirm.cancel', 'en', 'Keep cart'),
  ('ui', 'pos.closeConfirm.cancel', 'ar', 'الاحتفاظ بالسلة'),
  -- Scan + cart
  ('ui', 'pos.scan.placeholder', 'en', 'Scan or type a product code, then press Enter'),
  ('ui', 'pos.scan.placeholder', 'ar', 'امسح أو اكتب كود المنتج ثم اضغط Enter'),
  ('ui', 'pos.scan.label', 'en', 'Product code'),
  ('ui', 'pos.scan.label', 'ar', 'كود المنتج'),
  ('ui', 'pos.empty', 'en', 'No items yet — scan a product to begin.'),
  ('ui', 'pos.empty', 'ar', 'لا توجد عناصر بعد — امسح منتجًا للبدء.'),
  ('ui', 'pos.table.code', 'en', 'Code'),
  ('ui', 'pos.table.code', 'ar', 'الكود'),
  ('ui', 'pos.table.name', 'en', 'Product'),
  ('ui', 'pos.table.name', 'ar', 'المنتج'),
  ('ui', 'pos.table.price', 'en', 'Unit price'),
  ('ui', 'pos.table.price', 'ar', 'سعر الوحدة'),
  ('ui', 'pos.table.qty', 'en', 'Qty'),
  ('ui', 'pos.table.qty', 'ar', 'الكمية'),
  ('ui', 'pos.table.total', 'en', 'Total'),
  ('ui', 'pos.table.total', 'ar', 'الإجمالي'),
  ('ui', 'pos.table.actions', 'en', 'Actions'),
  ('ui', 'pos.table.actions', 'ar', 'إجراءات'),
  ('ui', 'pos.remove', 'en', 'Remove'),
  ('ui', 'pos.remove', 'ar', 'إزالة'),
  ('ui', 'pos.confirmVariant', 'en', 'Confirm variant'),
  ('ui', 'pos.confirmVariant', 'ar', 'تأكيد النوع'),
  ('ui', 'pos.finalizeRequired', 'en', 'Finalize the variant for {{name}} before checkout.'),
  ('ui', 'pos.finalizeRequired', 'ar', 'يرجى تحديد نوع المنتج {{name}} قبل الدفع.'),
  ('ui', 'pos.stats.items', 'en', 'Number of items'),
  ('ui', 'pos.stats.items', 'ar', 'عدد العناصر'),
  ('ui', 'pos.stats.discount', 'en', 'Discount'),
  ('ui', 'pos.stats.discount', 'ar', 'الخصم'),
  ('ui', 'pos.stats.total', 'en', 'Total Price'),
  ('ui', 'pos.stats.total', 'ar', 'السعر الإجمالي'),
  -- Warnings / errors (keys returned by the API)
  ('ui', 'pos.errors.notFound', 'en', 'Product code not found.'),
  ('ui', 'pos.errors.notFound', 'ar', 'كود المنتج غير موجود.'),
  ('ui', 'pos.errors.outOfStock', 'en', 'Not enough stock available for this product.'),
  ('ui', 'pos.errors.outOfStock', 'ar', 'لا يوجد مخزون كافٍ لهذا المنتج.'),
  ('ui', 'pos.errors.stock', 'en', 'Not enough stock to complete the sale.'),
  ('ui', 'pos.errors.stock', 'ar', 'لا يوجد مخزون كافٍ لإتمام البيع.'),
  ('ui', 'pos.errors.priceBelowMin', 'en', 'This product cannot be sold below its minimum price.'),
  ('ui', 'pos.errors.priceBelowMin', 'ar', 'لا يمكن بيع هذا المنتج بأقل من سعره الأدنى.'),
  ('ui', 'pos.errors.invalidPhone', 'en', 'Please enter a valid phone number.'),
  ('ui', 'pos.errors.invalidPhone', 'ar', 'يرجى إدخال رقم هاتف صحيح.'),
  ('ui', 'pos.priceAdjusted', 'en', 'Price adjusted to the minimum allowed for {{name}}.'),
  ('ui', 'pos.priceAdjusted', 'ar', 'تم تعديل السعر إلى الحد الأدنى المسموح لـ {{name}}.'),
  ('ui', 'pos.priceCapped', 'en', 'Price capped at the list price for {{name}}.'),
  ('ui', 'pos.priceCapped', 'ar', 'تم تحديد السعر بسعر البيع الأقصى لـ {{name}}.'),
  ('ui', 'pos.qtyCapped', 'en', 'Only {{count}} left in stock for this product.'),
  ('ui', 'pos.qtyCapped', 'ar', 'المتبقي في المخزون {{count}} فقط لهذا المنتج.'),
  -- Wizard
  ('ui', 'pos.step.cart', 'en', 'Cart'),
  ('ui', 'pos.step.cart', 'ar', 'السلة'),
  ('ui', 'pos.step.customer', 'en', 'Customer'),
  ('ui', 'pos.step.customer', 'ar', 'العميل'),
  ('ui', 'pos.step.invoice', 'en', 'Invoice'),
  ('ui', 'pos.step.invoice', 'ar', 'الفاتورة'),
  ('ui', 'pos.back', 'en', 'Back'),
  ('ui', 'pos.back', 'ar', 'رجوع'),
  ('ui', 'pos.next', 'en', 'Next'),
  ('ui', 'pos.next', 'ar', 'التالي'),
  ('ui', 'pos.cartEmpty', 'en', 'Add at least one item to continue.'),
  ('ui', 'pos.cartEmpty', 'ar', 'أضف عنصرًا واحدًا على الأقل للمتابعة.'),
  -- Customer step
  ('ui', 'pos.customer.title', 'en', 'Customer information'),
  ('ui', 'pos.customer.title', 'ar', 'معلومات العميل'),
  ('ui', 'pos.customer.phone', 'en', 'Phone number'),
  ('ui', 'pos.customer.phone', 'ar', 'رقم الهاتف'),
  ('ui', 'pos.customer.phoneHint', 'en', 'Enter a phone number to auto-fill an existing customer.'),
  ('ui', 'pos.customer.phoneHint', 'ar', 'أدخل رقم هاتف لملء بيانات عميل موجود تلقائيًا.'),
  ('ui', 'pos.customer.name', 'en', 'Customer name'),
  ('ui', 'pos.customer.name', 'ar', 'اسم العميل'),
  ('ui', 'pos.customer.existing', 'en', 'Existing customer'),
  ('ui', 'pos.customer.existing', 'ar', 'عميل موجود'),
  ('ui', 'pos.customer.nameRequired', 'en', 'Customer name is required.'),
  ('ui', 'pos.customer.nameRequired', 'ar', 'اسم العميل مطلوب.'),
  ('ui', 'pos.payment.title', 'en', 'Payment method'),
  ('ui', 'pos.payment.title', 'ar', 'طريقة الدفع'),
  ('ui', 'pos.payment.required', 'en', 'Please choose a payment method.'),
  ('ui', 'pos.payment.required', 'ar', 'يرجى اختيار طريقة دفع.'),
  ('ui', 'pos.payment.paid', 'en', 'Amount paid'),
  ('ui', 'pos.payment.paid', 'ar', 'المبلغ المدفوع'),
  ('ui', 'pos.payment.paidHint', 'en', 'If less than the total, it is set to the total automatically.'),
  ('ui', 'pos.payment.paidHint', 'ar', 'إذا كان أقل من الإجمالي، يتم ضبطه على الإجمالي تلقائيًا.'),
  ('ui', 'pos.payment.changeRaw', 'en', 'Change'),
  ('ui', 'pos.payment.changeRaw', 'ar', 'الباقي'),
  ('ui', 'pos.payment.changeExact', 'en', 'Exact change'),
  ('ui', 'pos.payment.changeExact', 'ar', 'الباقي الدقيق'),
  -- Invoice step
  ('ui', 'pos.invoice.title', 'en', 'Invoice'),
  ('ui', 'pos.invoice.title', 'ar', 'الفاتورة'),
  ('ui', 'pos.invoice.number', 'en', 'Invoice No.'),
  ('ui', 'pos.invoice.number', 'ar', 'رقم الفاتورة'),
  ('ui', 'pos.invoice.date', 'en', 'Date'),
  ('ui', 'pos.invoice.date', 'ar', 'التاريخ'),
  ('ui', 'pos.invoice.customer', 'en', 'Customer'),
  ('ui', 'pos.invoice.customer', 'ar', 'العميل'),
  ('ui', 'pos.invoice.payment', 'en', 'Payment'),
  ('ui', 'pos.invoice.payment', 'ar', 'الدفع'),
  ('ui', 'pos.invoice.print', 'en', 'Print'),
  ('ui', 'pos.invoice.print', 'ar', 'طباعة'),
  ('ui', 'pos.invoice.newSale', 'en', 'New Sale'),
  ('ui', 'pos.invoice.newSale', 'ar', 'عملية بيع جديدة'),
  ('ui', 'pos.invoice.done', 'en', 'Sale completed successfully.'),
  ('ui', 'pos.invoice.done', 'ar', 'تمت عملية البيع بنجاح.'),
  ('ui', 'pos.invoice.thanks', 'en', 'Thank you for your purchase!'),
  ('ui', 'pos.invoice.thanks', 'ar', 'شكرًا لتعاملكم معنا!'),
  ('ui', 'pos.invoice.draft', 'en', 'DRAFT'),
  ('ui', 'pos.invoice.draft', 'ar', 'مسودة'),
  ('ui', 'pos.invoice.paidBadge', 'en', 'Paid'),
  ('ui', 'pos.invoice.paidBadge', 'ar', 'مدفوعة'),
  ('ui', 'pos.invoice.billTo', 'en', 'Billed to'),
  ('ui', 'pos.invoice.billTo', 'ar', 'فاتورة إلى'),
  ('ui', 'pos.invoice.item', 'en', 'Item'),
  ('ui', 'pos.invoice.item', 'ar', 'الصنف'),
  ('ui', 'pos.invoice.subtotal', 'en', 'Subtotal'),
  ('ui', 'pos.invoice.subtotal', 'ar', 'المجموع الفرعي'),
  ('ui', 'pos.invoice.skip', 'en', 'Skip invoice'),
  ('ui', 'pos.invoice.skip', 'ar', 'تخطي الفاتورة'),
  ('ui', 'pos.invoice.skipped', 'en', 'Invoice skipped'),
  ('ui', 'pos.invoice.skipped', 'ar', 'تم تخطي الفاتورة'),
  ('ui', 'pos.invoice.checkout', 'en', 'Checkout'),
  ('ui', 'pos.invoice.checkout', 'ar', 'إتمام البيع');

-- Attribute global/coding buckets + variant stock units (redesign) -----------
INSERT IGNORE INTO `translations` (`namespace`, `key`, `locale`, `value`) VALUES
  ('ui', 'products.attrs.modal.global', 'en', 'Global'),
  ('ui', 'products.attrs.modal.global', 'ar', 'عام'),
  ('ui', 'products.attrs.modal.globalHint', 'en', 'One value shared across the whole product (turn off to set it per variant/stock).'),
  ('ui', 'products.attrs.modal.globalHint', 'ar', 'قيمة واحدة لكل المنتج (أوقفه لتحديدها لكل متغير/مخزون).'),
  ('ui', 'products.attrs.col.global', 'en', 'Global'),
  ('ui', 'products.attrs.col.global', 'ar', 'عام'),
  ('ui', 'products.attrs.errors.codingGlobal', 'en', 'Coding can only be enabled for non-global attributes.'),
  ('ui', 'products.attrs.errors.codingGlobal', 'ar', 'لا يمكن تفعيل الترميز إلا للخصائص غير العامة.'),
  ('ui', 'products.attrs.errors.bucketLocked', 'en', 'This attribute is in use, so its Global/Coding setting cannot be changed.'),
  ('ui', 'products.attrs.errors.bucketLocked', 'ar', 'هذه الخاصية قيد الاستخدام، لذا لا يمكن تغيير إعداد العام/الترميز.'),
  ('ui', 'products.modal.stockUnits', 'en', 'Stock units'),
  ('ui', 'products.modal.stockUnits', 'ar', 'وحدات المخزون'),
  ('ui', 'products.modal.addStock', 'en', 'Add stock unit'),
  ('ui', 'products.modal.addStock', 'ar', 'إضافة وحدة مخزون'),
  ('ui', 'products.modal.removeStock', 'en', 'Remove stock unit'),
  ('ui', 'products.modal.removeStock', 'ar', 'إزالة وحدة المخزون'),
  ('ui', 'pos.table.soldOut', 'en', 'Sold out'),
  ('ui', 'pos.table.soldOut', 'ar', 'نفد'),
  ('ui', 'pos.table.editPrice', 'en', 'Double-click to edit price'),
  ('ui', 'pos.table.editPrice', 'ar', 'انقر مرتين لتعديل السعر'),
  ('ui', 'pos.table.editQty', 'en', 'Double-click to edit quantity'),
  ('ui', 'pos.table.editQty', 'ar', 'انقر مرتين لتعديل الكمية'),
  ('ui', 'pos.table.category', 'en', 'Category'),
  ('ui', 'pos.table.category', 'ar', 'الفئة');
